spring:
  application:
    name: ms-gateway
server:
  port: 8080
  error:
    include-stacktrace: never

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

jwtdemo:
  secretKey: dünyaninEnGizliAnahtari1939BatuhanTibiaBrno<3JavaciMiyimAbi?