spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/v1/customer/**
      discovery:
        locator:
          enabled: true
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
